function [singleTraninsee] = plotSingleTransaction(edgeStat, edgePile, edgePassed1, edgePassed2)
    load flatNodeArray.mat flatNodeArray
    M = size(edgeStat, 1);
    singleTraninsee = figure("Name", "Single Traninsee");
    hold on
    for i = 1 : M
        plot([flatNodeArray{edgeStat(i, 1) + 1}.x, flatNodeArray{edgeStat(i, 2) + 1}.x], ...
        [flatNodeArray{edgeStat(i, 1) + 1}.y, flatNodeArray{edgeStat(i, 2) + 1}.y], ...
        '-bo', 'MarkerSize', 3,...
        'MarkerEdgeColor', 'b',...
        'MarkerFaceColor', 'b')
    end
    
    for i = 1 : size(edgePassed2, 1)
        edgeID = edgePassed2(i) + 1;
        plot([flatNodeArray{edgePile(edgeID, 1) + 1}.x, flatNodeArray{edgePile(edgeID, 2) + 1}.x], ...
        [flatNodeArray{edgePile(edgeID, 1) + 1}.y, flatNodeArray{edgePile(edgeID, 2) + 1}.y], ...
        '-ro', 'MarkerSize', 3,...
        'MarkerEdgeColor', 'b',...
        'MarkerFaceColor', 'b')
    end
    
    for i = 1 : size(edgePassed1, 1)
        edgeID = edgePassed1(i) + 1;
        plot([flatNodeArray{edgePile(edgeID, 1) + 1}.x, flatNodeArray{edgePile(edgeID, 2) + 1}.x], ...
        [flatNodeArray{edgePile(edgeID, 1) + 1}.y, flatNodeArray{edgePile(edgeID, 2) + 1}.y], ...
        '-go', 'MarkerSize', 3,...
        'MarkerEdgeColor', 'b',...
        'MarkerFaceColor', 'b')
    end
    h(1) = plot(nan, nan, '-g', 'LineWidth', 1);
    h(2) = plot(nan, nan, '-r', 'LineWidth', 1);
    legend(h, {'Ideal Path', 'Actual Path'}, 'Box', 'off', 'FontSize', 10, 'Location', 'northeastoutside', 'Orientation', 'vertical');
    axis off
    hold off
end

